on: [pull_request]

name: Test

jobs:
  check:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          npm ci
          npm test
